### ISSUE TITLE
Error authenticating

### ISSUE THREAD

**Issue by andig** [wez3/volkswagen-carnet-client#17]
Looks like I'm not successful using `carnet-app`:

```
Logging in
Traceback (most recent call last):
  File "vw.py", line 175, in <module>
    token = carNetLogon()
  File "vw.py", line 25, in carNetLogon
    HEADERS["Authorization"] = "AudiAuth 1 " + token
TypeError: can only concatenate str (not "NoneType") to str
```

and

```
{
                "error":"invalid_grant",
                "error_description":
                "Error authenticating"
}
```

Could anybody confirm that this should still be working in Germany today? I've used email address as username- is that correct?

/cc @TMD-Burger

**Comment by nheuk** [comment]
same problem :-(

**Comment by jochenpee** [comment]
VW closed down the website, so this is no longer working. I hope someone uses the app interface for a script, I am not capable of doing this.
